import type { ActivityCategory, Frequency, LeadImpact, Performer, ProofKind } from "./meta";

/**
 * The base template: every recurring activity that keeps a brand's social
 * presence current and turns it into a source of leads.
 *
 * Every brand works from this same list. An activity with no `platforms` is
 * done on each platform the brand is on; one with `platforms` is extra work
 * that only exists where the brand has one of those channels.
 *
 * `code` is the permanent id. Seeding matches on it, agents address activities
 * by it and history hangs off it, so never renumber — retire a code and add a
 * new one instead.
 */
export type LibraryActivity = {
  code: string;
  frequency: Frequency;
  category: ActivityCategory;
  title: string;
  /** How to do it well, in a sentence or three. */
  description: string;
  /** How many make it "done" for the period. */
  target: number;
  unit: string;
  proof: ProofKind;
  performer: Performer;
  leadImpact: LeadImpact;
  /** Rough effort per period, so a plan can be sized to the hours available. */
  minutes: number;
  platforms: string[];
};

type Opts = Partial<Pick<LibraryActivity, "target" | "unit" | "proof" | "performer" | "leadImpact" | "minutes" | "platforms">>;
type Row = [code: string, category: ActivityCategory, title: string, description: string, opts?: Opts];

function group(frequency: Frequency, rows: Row[]): LibraryActivity[] {
  return rows.map(([code, category, title, description, o = {}]) => ({
    code, frequency, category, title, description,
    target: o.target ?? 1,
    unit: o.unit ?? "time",
    proof: o.proof ?? "note",
    performer: o.performer ?? "human",
    leadImpact: o.leadImpact ?? "medium",
    minutes: o.minutes ?? 15,
    platforms: o.platforms ?? [],
  }));
}

const SHORT_VIDEO = ["instagram", "tiktok", "youtube", "facebook"];
const LIVE = ["linkedin", "facebook", "instagram", "youtube", "x", "tiktok", "twitch"];
const REVIEW_SITES = ["google_business", "trustpilot", "clutch", "g2", "capterra", "yelp", "tripadvisor"];
const LISTINGS = ["google_business", "apple_business", "bing_places", "yelp", "clutch", "g2", "capterra", "trustpilot"];

/* ================================================================== daily */

const DAILY = group("daily", [
  // First on purpose: nothing else on the list counts if the page itself is gone.
  ["D-00", "presence", "Confirm each channel's page URL is live",
    "Open the brand's page on every channel in a private window. Check it loads, is the brand's own page (not suspended, restricted, renamed or taken over) and the handle still matches. If a page has gone, stop and tell the owner before doing anything else on that channel. ggsocial visits every saved page URL every six hours and ticks this itself; finish by hand any page it couldn't confirm.",
    { unit: "page per channel", proof: "link", performer: "either", leadImpact: "high", minutes: 5 }],
  ["D-01", "content", "Publish today's planned post",
    "Publish the post from the content plan on every active platform, adapted to each one's format. Every post ends with one clear next step (comment, DM, visit, book).",
    { unit: "post per platform", proof: "link", performer: "either", leadImpact: "high", minutes: 20 }],
  ["D-02", "engagement", "Reply to every comment on our posts",
    "Answer every comment on our own posts within the brand's reply SLA. Ask a follow-up question so the thread keeps going.",
    { unit: "all comments", proof: "count", performer: "either", leadImpact: "high", minutes: 20 }],
  ["D-03", "outreach", "Reply to all private messages",
    "Clear the inbox on every platform: DMs, page messages, message requests. Qualify anyone showing buying intent and log them as a lead.",
    { unit: "all messages", proof: "count", leadImpact: "high", minutes: 20 }],
  ["D-04", "engagement", "Like or react to comments on our posts",
    "React to every comment on today's and yesterday's posts so commenters feel seen and come back.",
    { unit: "all comments", proof: "count", performer: "either", leadImpact: "low", minutes: 5 }],
  ["D-05", "engagement", "Comment on posts from prospects",
    "Leave thoughtful comments (two sentences or more, adding a point of view) on posts by ideal customers. This is the fastest way to be noticed by buyers.",
    { target: 5, unit: "comments", proof: "count", leadImpact: "high", minutes: 20 }],
  ["D-06", "engagement", "Comment on posts from industry voices",
    "Add useful comments on posts by influencers, analysts and leaders in the niche. Their audiences are our prospects.",
    { target: 3, unit: "comments", proof: "count", minutes: 15 }],
  ["D-07", "networking", "Send personalised connection or follow requests",
    "Connect with or follow people who match the ideal-customer profile, each with a short personal note. Never pitch in the first message.",
    { target: 5, unit: "requests", proof: "count", leadImpact: "high", minutes: 15 }],
  ["D-08", "outreach", "Welcome new connections and followers",
    "Send a short, no-pitch welcome message to new connections. Thank them and ask one question about their work.",
    { unit: "all new", proof: "count", performer: "either", leadImpact: "high", minutes: 10 }],
  ["D-09", "outreach", "Follow up on open lead conversations",
    "Move every live lead conversation one step on: answer the question, share the resource, suggest a call.",
    { unit: "all open threads", proof: "count", leadImpact: "high", minutes: 15 }],
  ["D-10", "engagement", "Check notifications, mentions and tags",
    "Go through notifications on every platform. Thank people who mention or tag the brand, and reply where a reply helps.",
    { proof: "count", performer: "either", minutes: 10 }],
  ["D-11", "engagement", "Share or repost one relevant post",
    "Reshare a post from a client, partner, employee or industry voice, adding our own comment on why it matters.",
    { proof: "link", performer: "either", leadImpact: "low", minutes: 5 }],
  ["D-12", "outreach", "Log new leads in the pipeline",
    "Every enquiry, warm DM or demo request goes into the CRM or engagement queue, with the platform and post it came from.",
    { unit: "all new leads", proof: "count", performer: "either", leadImpact: "high", minutes: 10 }],
  ["D-13", "reputation", "Check and respond to new reviews",
    "Look for new reviews on every review site and platform. Thank positive ones by name, and answer negative ones calmly with an offer to fix it offline.",
    { unit: "all new reviews", proof: "count", performer: "either", leadImpact: "high", minutes: 10 }],
  ["D-14", "community", "Answer questions in groups and forums",
    "Answer questions in groups, subreddits and forums where customers ask for help. Be genuinely useful; link only when the rules allow.",
    { target: 2, unit: "answers", proof: "link", leadImpact: "high", minutes: 20 }],
  ["D-15", "engagement", "Continue threads we commented in",
    "Go back to yesterday's comments on other people's posts and reply to anyone who responded to us.",
    { proof: "count", minutes: 10 }],
  ["D-16", "analytics", "Glance at yesterday's post performance",
    "Check reach and engagement on yesterday's posts. Flag anything unusually good or bad in the content plan notes.",
    { proof: "note", performer: "ai", leadImpact: "low", minutes: 5 }],
  ["D-17", "content", "Post a story",
    "Post at least one story: behind the scenes, a poll or quiz sticker, a reshare of today's post, or a link sticker to the offer.",
    { proof: "screenshot", performer: "either", minutes: 10, platforms: ["instagram", "facebook"] }],
  ["D-18", "networking", "Handle pending connection invitations",
    "Accept relevant invitations, ignore spam, and send a thank-you note to prospects who connected.",
    { proof: "count", leadImpact: "high", minutes: 10, platforms: ["linkedin"] }],
  ["D-19", "engagement", "Join niche conversations on X",
    "Reply to posts in niche conversations and trending topics where the brand has something useful to add.",
    { target: 5, unit: "replies", proof: "count", minutes: 15, platforms: ["x", "threads", "bluesky"] }],
  ["D-20", "engagement", "Reply to story replies and reel comments",
    "Answer story replies, reel comments and DMs that came from stories. Story replies are warm leads.",
    { proof: "count", leadImpact: "high", minutes: 10, platforms: ["instagram"] }],
  ["D-21", "engagement", "Reply to comments with a video reply",
    "Pick the best comment on a recent video and answer it with a short video reply. Reply in text to the rest.",
    { proof: "link", minutes: 15, platforms: ["tiktok"] }],
  ["D-22", "engagement", "Reply to and heart YouTube comments",
    "Reply to and heart comments on recent videos, and pin the most useful comment on the latest upload.",
    { proof: "count", performer: "either", minutes: 10, platforms: ["youtube"] }],
  ["D-23", "outreach", "Answer Google Business messages and Q&A",
    "Reply to chats and questions on the Google Business Profile. Local buyers who ask here are close to deciding.",
    { proof: "count", leadImpact: "high", minutes: 10, platforms: ["google_business"] }],
  ["D-24", "community", "Engage in target subreddits",
    "Upvote, comment and answer in two target subreddits without self-promotion. Build karma and credibility first.",
    { target: 2, unit: "subreddits", proof: "link", minutes: 15, platforms: ["reddit"] }],
  ["D-25", "engagement", "Moderate our page's comments",
    "Hide spam and scams, remove abusive comments, and ban repeat offenders so real prospects see a clean page.",
    { proof: "count", performer: "either", leadImpact: "low", minutes: 5, platforms: ["facebook", "instagram", "youtube"] }],
  ["D-26", "outreach", "Reply to WhatsApp and Telegram enquiries",
    "Answer every enquiry in business messaging apps and move qualified ones to a call or proposal.",
    { proof: "count", leadImpact: "high", minutes: 10, platforms: ["whatsapp", "telegram", "messenger"] }],
  ["D-27", "analytics", "Review the playbook's suggested changes",
    "Open Playbook → Daily review. Approve the changes the numbers back (posting times from the daily tuning job, agents' and editors' suggestions), reject the rest with a reason, and tune any rule that kept blocking good work yesterday. Agents: GET /api/agent/playbook/adjustments?status=proposed, then decide each.",
    { unit: "all open suggestions", proof: "note", performer: "either", leadImpact: "medium", minutes: 5 }],
]);

/* =========================================================== every 2 days */

const EVERY_2_DAYS = group("every_2_days", [
  ["2D-01", "content", "Publish a short-form video",
    "Post a reel, short or TikTok: a tip, myth-buster, quick demo or client result, under 60 seconds with captions and a hook in the first two seconds.",
    { proof: "link", performer: "either", leadImpact: "high", minutes: 45, platforms: SHORT_VIDEO }],
  ["2D-02", "networking", "Congratulate connections on milestones",
    "Send congratulations on new jobs, work anniversaries, promotions and birthdays. It's the easiest reason to restart a conversation.",
    { target: 3, unit: "messages", proof: "count", minutes: 10, platforms: ["linkedin", "facebook"] }],
  ["2D-03", "content", "Post a quick tip or short thread",
    "Share one practical tip, stat or opinion as a short post or thread. Text-only posts keep the account active between bigger pieces.",
    { proof: "link", performer: "either", minutes: 15, platforms: ["x", "threads", "bluesky", "linkedin"] }],
  ["2D-04", "outreach", "Follow up with leads that went quiet",
    "Send a light, useful nudge (a resource, a relevant post, a question) to leads with no reply in five days or more.",
    { target: 3, unit: "follow-ups", proof: "count", leadImpact: "high", minutes: 15 }],
  ["2D-05", "community", "Post a value comment in a group",
    "Add a substantial, non-promotional contribution to a Facebook, LinkedIn or Slack group discussion.",
    { proof: "link", minutes: 15 }],
  ["2D-06", "content", "Share a behind-the-scenes moment",
    "Show the people, process or workspace behind the brand: a story, photo or short clip. Trust converts leads.",
    { proof: "link", minutes: 10 }],
  ["2D-07", "engagement", "Engage with existing customers' content",
    "Like, comment on and share posts by current clients. It deepens relationships and gets us seen by their networks.",
    { target: 3, unit: "customers", proof: "count", minutes: 10 }],
]);

/* ================================================================= weekly */

const WEEKLY = group("weekly", [
  ["W-01", "content", "Plan and schedule next week's content",
    "Pick next week's posts from the content plan, draft them for each platform and schedule them in ggsocial.",
    { proof: "note", performer: "either", leadImpact: "high", minutes: 60 }],
  ["W-02", "content", "Publish a long-form piece",
    "Publish an article, blog post or newsletter with real depth, and promote it with a native post on each platform.",
    { proof: "link", performer: "either", leadImpact: "high", minutes: 90 }],
  ["W-03", "content", "Run a poll or question post",
    "Ask the audience a poll or open question about a real pain point. Voters and commenters are warm leads to follow up.",
    { proof: "link", performer: "either", leadImpact: "high", minutes: 10 }],
  ["W-04", "content", "Publish a carousel or document post",
    "Turn a framework, checklist or step-by-step guide into a swipeable carousel or PDF post. Saves and shares help reach.",
    { proof: "link", performer: "either", minutes: 45 }],
  ["W-05", "content", "Share a customer testimonial or result",
    "Post a client quote, before-and-after or result, with permission. Social proof is the post type most likely to bring enquiries.",
    { proof: "link", leadImpact: "high", minutes: 20 }],
  ["W-06", "content", "Publish an educational how-to video",
    "Record a longer how-to or walkthrough that answers a question customers really ask.",
    { proof: "link", leadImpact: "high", minutes: 90 }],
  ["W-07", "content", "Run a story Q&A or quiz",
    "Use a question, quiz or poll sticker in stories and answer the replies publicly or by DM.",
    { proof: "screenshot", minutes: 15, platforms: ["instagram", "facebook"] }],
  ["W-08", "outreach", "Send value-first DMs to warm prospects",
    "Message people who liked, commented or viewed this week, with something useful (a resource, an insight or an invite), not a pitch.",
    { target: 10, unit: "DMs", proof: "count", leadImpact: "high", minutes: 30 }],
  ["W-09", "outreach", "Reach out to profile viewers",
    "Review who viewed the profile or page this week and connect with, or message, the ones who fit the customer profile.",
    { target: 5, unit: "people", proof: "count", leadImpact: "high", minutes: 15, platforms: ["linkedin"] }],
  ["W-10", "networking", "Support partners' and referrers' content",
    "Comment on and share posts by referral partners, suppliers and collaborators. Reciprocity keeps referrals coming.",
    { target: 5, unit: "partners", proof: "count", minutes: 15 }],
  ["W-11", "community", "Join new relevant groups",
    "Find and join groups, subreddits, Slack or Discord communities where ideal customers gather. Read the rules first.",
    { target: 2, unit: "groups", proof: "link", minutes: 15 }],
  ["W-12", "community", "Post a value post in groups",
    "Start a useful discussion or share a genuinely helpful resource in two groups. No hard selling.",
    { target: 2, unit: "posts", proof: "link", leadImpact: "high", minutes: 30 }],
  ["W-13", "reputation", "Request reviews from happy customers",
    "Ask recently delighted customers for a review on the review site that matters most, with a direct link that makes it a one-minute job.",
    { target: 3, unit: "requests", proof: "count", leadImpact: "high", minutes: 15 }],
  ["W-14", "reputation", "Give reviews or recommendations to partners",
    "Write honest reviews, recommendations or endorsements for suppliers, partners and clients. It builds goodwill and often comes back.",
    { target: 2, unit: "reviews", proof: "link", minutes: 20 }],
  ["W-15", "analytics", "Weekly performance review",
    "Record reach, engagement rate, follower growth, link clicks and leads per platform in one line each. Note what moved.",
    { proof: "note", performer: "ai", leadImpact: "medium", minutes: 30 }],
  ["W-16", "analytics", "Review top and bottom posts",
    "Compare the three best and three worst posts of the week. Write one learning each into the content plan.",
    { proof: "note", performer: "ai", minutes: 20 }],
  ["W-17", "outreach", "Weekly lead review and hand-off",
    "Count leads by platform, update each one's stage, and hand qualified leads to sales with context.",
    { proof: "count", leadImpact: "high", minutes: 30 }],
  ["W-18", "engagement", "Thank top engagers publicly",
    "Give a shout-out, tag or reshare to the people who engaged most this week. It turns fans into advocates.",
    { proof: "link", performer: "either", leadImpact: "low", minutes: 10 }],
  ["W-19", "content", "Refresh hashtags and keywords",
    "Check which hashtags and keywords are trending in the niche and update the brand's default hashtag set.",
    { proof: "note", performer: "ai", leadImpact: "low", minutes: 15 }],
  ["W-20", "analytics", "Watch competitors' activity",
    "Look at what competitors posted and how it performed. Note ideas and gaps to use, and don't copy.",
    { proof: "note", performer: "ai", leadImpact: "low", minutes: 20 }],
  ["W-21", "content", "Repurpose the best post of the week",
    "Turn the week's top post into another format (carousel to video, thread to article) for another platform.",
    { proof: "link", performer: "either", minutes: 30 }],
  ["W-22", "profile", "Update the pinned or featured post",
    "Pin the best recent post or the current offer to the top of each profile.",
    { proof: "link", leadImpact: "medium", minutes: 10 }],
  ["W-23", "networking", "Connect with event and webinar attendees",
    "Send connection requests to people who attended, or engaged with, events, lives or webinars this week.",
    { target: 10, unit: "requests", proof: "count", leadImpact: "high", minutes: 20 }],
  ["W-24", "outreach", "Send the email newsletter",
    "Send the weekly newsletter with a clear call to action and link it from social profiles.",
    { proof: "link", performer: "either", leadImpact: "high", minutes: 45, platforms: ["mailchimp", "brevo", "convertkit", "klaviyo", "beehiiv", "substack"] }],
  ["W-25", "content", "Publish a Google Business update",
    "Post an update, offer or event to the Google Business Profile and add three new photos. Fresh profiles rank higher in local search.",
    { proof: "link", performer: "either", leadImpact: "high", minutes: 20, platforms: ["google_business"] }],
  ["W-26", "content", "Create and pin new Pins",
    "Create five fresh Pins linking to the site or offers and save them to keyword-named boards.",
    { target: 5, unit: "pins", proof: "link", performer: "either", minutes: 30, platforms: ["pinterest"] }],
  ["W-27", "content", "Upload an optimised YouTube video",
    "Upload one video with a keyword-rich title, description, chapters, tags, custom thumbnail, end screen and link to the offer.",
    { proof: "link", leadImpact: "high", minutes: 120, platforms: ["youtube"] }],
  ["W-28", "content", "Post on both the company page and founder profile",
    "Publish on the company page and on the founder's or leaders' personal profiles, then have staff engage in the first hour.",
    { proof: "link", leadImpact: "high", minutes: 30, platforms: ["linkedin"] }],
  ["W-29", "networking", "Invite engaged people to follow the page",
    "Use the weekly page-invite credits (LinkedIn) or 'invite to like' (Facebook) on people who engaged with posts.",
    { proof: "count", minutes: 10, platforms: ["linkedin", "facebook"] }],
  ["W-30", "community", "Publish a high-value subreddit post",
    "Share a genuinely useful post (a guide, data or lessons learned) in a target subreddit, following its self-promo rules.",
    { proof: "link", leadImpact: "high", minutes: 45, platforms: ["reddit"] }],
  ["W-31", "community", "Answer questions on Quora",
    "Answer three questions in the niche with detailed, expert answers, linking to a relevant resource where allowed.",
    { target: 3, unit: "answers", proof: "link", minutes: 45, platforms: ["quora"] }],
  ["W-32", "profile", "Update story Highlights",
    "Add the week's best stories to the right Highlights (Services, Results, FAQ, Reviews) and retire outdated ones.",
    { proof: "screenshot", minutes: 10, platforms: ["instagram"] }],
  ["W-33", "content", "Post a trend-based video",
    "Make a video using a current trend, sound or format, adapted to the brand's message.",
    { proof: "link", minutes: 45, platforms: ["tiktok", "instagram"] }],
  ["W-34", "content", "Post in the YouTube Community tab",
    "Share a poll, image or update in the Community tab to keep subscribers engaged between uploads.",
    { proof: "link", performer: "either", leadImpact: "low", minutes: 10, platforms: ["youtube", "youtube_community"] }],
]);

/* ================================================================ monthly */

const MONTHLY = group("monthly", [
  ["M-01", "content", "Host a live session",
    "Go live (Q&A, demo, expert interview, workshop) or host an audio room. Promote it a week ahead and follow up with every attendee.",
    { proof: "link", leadImpact: "high", minutes: 120, platforms: LIVE }],
  ["M-02", "content", "Publish a case study",
    "Publish a full client story (problem, approach, result, quote) and cut it into posts for every platform.",
    { proof: "link", leadImpact: "high", minutes: 120 }],
  ["M-03", "content", "Publish a monthly roundup",
    "Share a monthly roundup: best content, news, wins and what's coming. It works as a post, newsletter or LinkedIn newsletter.",
    { proof: "link", performer: "either", minutes: 45 }],
  ["M-04", "profile", "Audit bios, links and contact details",
    "On every platform, check that the bio, website, link-in-bio, phone, email, address, hours and CTA button are correct and consistent.",
    { proof: "note", performer: "either", leadImpact: "high", minutes: 45 }],
  ["M-05", "profile", "Refresh cover and banner images",
    "Update cover and banner images to show the current campaign, offer or event.",
    { proof: "screenshot", minutes: 30 }],
  ["M-06", "profile", "Test every profile link",
    "Click every link in bios, pinned posts and featured sections. Fix any 404s and make sure links use tracked short links.",
    { proof: "note", performer: "ai", leadImpact: "high", minutes: 20 }],
  ["M-07", "profile", "Add new services, products or portfolio items",
    "Add anything new to profile sections: LinkedIn Services and Featured, Facebook shop, Google Business products, portfolio pieces.",
    { proof: "link", leadImpact: "high", minutes: 30 }],
  ["M-08", "reputation", "Audit and answer unanswered reviews",
    "Search every review site for reviews without a reply, including old ones, and answer each.",
    { proof: "count", performer: "either", leadImpact: "medium", minutes: 30, platforms: REVIEW_SITES }],
  ["M-09", "reputation", "Send a review request campaign",
    "Email or message everyone who became a customer last month asking for a review, with direct links.",
    { proof: "count", performer: "either", leadImpact: "high", minutes: 30 }],
  ["M-10", "networking", "Connect with new partners and referral sources",
    "Find and connect with complementary businesses, agencies and consultants who serve the same customers.",
    { target: 10, unit: "partners", proof: "count", leadImpact: "high", minutes: 45 }],
  ["M-11", "networking", "Reconnect with dormant contacts",
    "Send a personal check-in to past clients, old leads and quiet connections. Many deals come from people who already know us.",
    { target: 10, unit: "people", proof: "count", leadImpact: "high", minutes: 30 }],
  ["M-12", "community", "Review group memberships",
    "Leave inactive or spammy groups and note which groups actually produced conversations or leads.",
    { proof: "note", leadImpact: "low", minutes: 20 }],
  ["M-13", "community", "Host or join a community event or AMA",
    "Run an Ask-Me-Anything, attend a virtual meetup or co-host a group session to meet buyers where they gather.",
    { proof: "link", leadImpact: "high", minutes: 90 }],
  ["M-14", "analytics", "Monthly social media report",
    "Follower growth, engagement rate, reach, clicks, leads and conversions by platform against targets, with three actions for next month.",
    { proof: "link", performer: "ai", leadImpact: "medium", minutes: 60 }],
  ["M-15", "analytics", "Benchmark competitors",
    "Record competitors' followers, posting frequency, engagement and top content. Note one thing to try.",
    { proof: "note", performer: "ai", leadImpact: "low", minutes: 45 }],
  ["M-16", "analytics", "Update the content plan with learnings",
    "Move the month's learnings into the content plan: more of what worked, less of what didn't, new pillars or series.",
    { proof: "note", performer: "either", minutes: 30 }],
  ["M-17", "outreach", "Audit the social lead pipeline",
    "Review every open lead from social: who needs a follow-up, which deals stalled, where leads are leaking.",
    { proof: "note", leadImpact: "high", minutes: 45 }],
  ["M-18", "admin", "Review who has access to each account",
    "Check admins and roles on every platform, and remove people and apps that no longer need access.",
    { proof: "note", leadImpact: "low", minutes: 30 }],
  ["M-19", "admin", "Check connected channels in ggsocial",
    "Reconnect expired or errored channels and fix failing auto-publishing before it costs a week of posts.",
    { proof: "note", performer: "either", leadImpact: "low", minutes: 15 }],
  ["M-20", "content", "Co-create a post with a partner or customer",
    "Make a collaborative post, interview or joint live with a partner, client or micro-influencer to reach their audience.",
    { proof: "link", leadImpact: "high", minutes: 60 }],
  ["M-21", "content", "Share a content kit with the team",
    "Send employees ready-to-share posts and images, and ask them to share and comment. Staff networks reach further than the brand page.",
    { proof: "note", performer: "either", minutes: 30 }],
  ["M-22", "engagement", "Clean up spam and bot followers",
    "Remove obvious bot and spam followers so engagement rates and targeting stay accurate.",
    { proof: "count", leadImpact: "low", minutes: 20, platforms: ["instagram", "x", "tiktok", "facebook"] }],
  ["M-23", "outreach", "Invite engaged followers to an offer or event",
    "Personally invite the month's most engaged followers to a webinar, consultation, trial or newsletter.",
    { target: 10, unit: "invites", proof: "count", leadImpact: "high", minutes: 30 }],
  ["M-24", "content", "Publish a LinkedIn newsletter edition",
    "Publish the monthly LinkedIn newsletter. Subscribers are notified, which makes it one of the highest-reach formats on the platform.",
    { proof: "link", performer: "either", leadImpact: "high", minutes: 90, platforms: ["linkedin"] }],
  ["M-25", "networking", "Withdraw stale connection invitations",
    "Withdraw invitations pending more than three weeks to keep the account in good standing and free up weekly invite limits.",
    { proof: "count", leadImpact: "low", minutes: 10, platforms: ["linkedin"] }],
  ["M-26", "reputation", "Request and give LinkedIn recommendations",
    "Ask two happy clients or colleagues for a recommendation, give two in return, and endorse relevant skills.",
    { target: 2, unit: "each way", proof: "count", minutes: 20, platforms: ["linkedin"] }],
  ["M-27", "profile", "Update Google Business details",
    "Check hours, special or holiday hours, attributes, services, products, service areas and booking link. Read the Insights.",
    { proof: "note", performer: "either", leadImpact: "high", minutes: 20, platforms: ["google_business"] }],
  ["M-28", "profile", "Tidy YouTube playlists and channel page",
    "Organise new videos into playlists, update the channel trailer and featured sections, and check descriptions link to offers.",
    { proof: "note", minutes: 30, platforms: ["youtube"] }],
  ["M-29", "profile", "Review the Facebook page About and CTA",
    "Update the page's About, services, CTA button, auto-replies and FAQs in Messenger.",
    { proof: "note", minutes: 20, platforms: ["facebook"] }],
  ["M-30", "profile", "Update link-in-bio and Highlight covers",
    "Point the link-in-bio at the current offers and refresh Highlight covers to match the brand.",
    { proof: "screenshot", minutes: 15, platforms: ["instagram", "tiktok"] }],
  ["M-31", "profile", "Update the pinned post and lists on X",
    "Refresh the pinned post with the current best offer and prune or grow the prospect and industry lists.",
    { proof: "link", leadImpact: "low", minutes: 15, platforms: ["x"] }],
  ["M-32", "profile", "Optimise Pinterest boards",
    "Rename boards with search keywords, write board descriptions, reorder the best boards to the top and archive dead ones.",
    { proof: "note", leadImpact: "low", minutes: 20, platforms: ["pinterest"] }],
  ["M-33", "profile", "Update review and directory listings",
    "Refresh details, services, pricing, portfolio and screenshots on Clutch, G2, Capterra, Trustpilot and similar listings.",
    { proof: "link", leadImpact: "high", minutes: 30, platforms: ["clutch", "g2", "capterra", "trustpilot", "upwork", "fiverr", "product_hunt"] }],
]);

/* ============================================================== quarterly */

const QUARTERLY = group("quarterly", [
  ["Q-01", "analytics", "Quarterly strategy review",
    "Compare goals with actuals per platform: followers, engagement, leads, pipeline and revenue from social. Decide what to double down on and what to drop.",
    { proof: "link", performer: "either", leadImpact: "high", minutes: 120 }],
  ["Q-02", "content", "Plan next quarter's content pillars and campaigns",
    "Set the themes, campaigns, launches and key dates for the next quarter and load them into the content plan.",
    { proof: "note", performer: "either", leadImpact: "high", minutes: 120 }],
  ["Q-03", "profile", "Full profile audit on every platform",
    "Check photos, names, handles, bios, keywords, CTAs, links and contact details against the brand book everywhere. Fix inconsistencies.",
    { proof: "note", performer: "either", leadImpact: "high", minutes: 90 }],
  ["Q-04", "profile", "Align team members' profiles",
    "Make sure staff profiles show the right job title, company page link, banner and a line about what the company does.",
    { proof: "note", minutes: 60, platforms: ["linkedin"] }],
  ["Q-05", "reputation", "Review rating trends and testimonials",
    "Look at rating trends and repeated themes in reviews. Fix what the complaints point to, and add the best reviews to a testimonials library.",
    { proof: "note", performer: "either", leadImpact: "medium", minutes: 60 }],
  ["Q-06", "content", "Run a campaign, contest or challenge",
    "Run a giveaway, contest, challenge or UGC campaign that grows the audience with the right people, following each platform's rules.",
    { proof: "link", leadImpact: "high", minutes: 240 }],
  ["Q-07", "content", "Launch and promote a lead magnet",
    "Publish a guide, checklist, template or mini-course behind a sign-up form and promote it on every platform.",
    { proof: "link", leadImpact: "high", minutes: 240 }],
  ["Q-08", "networking", "Reach out to collaboration partners or influencers",
    "Pitch collaborations (guest posts, joint lives, co-marketing) to five partners or creators who share the target audience.",
    { target: 5, unit: "pitches", proof: "count", leadImpact: "high", minutes: 60 }],
  ["Q-09", "community", "Review the brand's own community",
    "Decide whether to start or grow a brand-owned group or community, and set its goal and posting rhythm.",
    { proof: "note", minutes: 45 }],
  ["Q-10", "admin", "Security review of every account",
    "Check that 2FA is on, passwords are strong and stored in the password manager, recovery emails and phones are the company's, and there are no unknown sessions.",
    { proof: "note", leadImpact: "low", minutes: 60 }],
  ["Q-11", "analytics", "Audience analysis",
    "Review audience demographics, locations, job titles and active hours. Adjust targeting and posting times to match the ideal customer.",
    { proof: "note", performer: "ai", minutes: 45 }],
  ["Q-12", "analytics", "Hashtag and keyword strategy review",
    "Review which hashtags and search keywords brought reach and leads, and rebuild the sets for next quarter.",
    { proof: "note", performer: "ai", leadImpact: "low", minutes: 30 }],
  ["Q-13", "profile", "Refresh photos and visuals",
    "Take or source new headshots, team, workspace and product photos so profiles and galleries don't look stale.",
    { proof: "link", minutes: 120 }],
  ["Q-14", "content", "Republish top evergreen content",
    "Update and re-share the best-performing evergreen posts from earlier quarters with a new angle.",
    { target: 3, unit: "posts", proof: "link", performer: "either", minutes: 45 }],
  ["Q-15", "outreach", "Re-engagement campaign for past leads",
    "Message leads that didn't convert and past clients with something new: an offer, case study or invitation.",
    { proof: "count", leadImpact: "high", minutes: 90 }],
  ["Q-16", "profile", "Claim and verify new listings",
    "Search for unclaimed or duplicate listings (Google, Apple, Bing, Yelp, directories). Claim, verify, merge and complete them.",
    { proof: "link", leadImpact: "high", minutes: 60, platforms: LISTINGS }],
  ["Q-17", "content", "Test a new format or platform",
    "Try one new format (live, audio, carousel, long video) or a new platform for the quarter, and measure it against the norm.",
    { proof: "note", minutes: 60 }],
  ["Q-18", "analytics", "Review paid and boosted post results",
    "Review spend, cost per lead and results of boosted posts and ads, and decide next quarter's budget per platform.",
    { proof: "note", performer: "either", leadImpact: "medium", minutes: 45 }],
  ["Q-19", "profile", "Optimise YouTube channel SEO",
    "Refresh channel keywords, the description, playlist titles and the titles and thumbnails of the older videos that get the most views.",
    { proof: "note", performer: "either", minutes: 60, platforms: ["youtube"] }],
]);

/* ============================================================ six-monthly */

const HALF_YEARLY = group("half_yearly", [
  ["H-01", "profile", "Brand consistency audit",
    "Check logos, colours, names, handles and messaging across every platform against the brand book. Fix anything off-brand.",
    { proof: "note", performer: "either", minutes: 90 }],
  ["H-02", "profile", "Refresh profile pictures",
    "Update profile photos and logos where they're outdated, blurry or inconsistent, keeping them recognisable.",
    { proof: "screenshot", leadImpact: "low", minutes: 30 }],
  ["H-03", "analytics", "Six-month ROI review by platform",
    "Rank platforms by leads and revenue per hour spent. Move time from the weakest to the strongest.",
    { proof: "link", performer: "either", leadImpact: "high", minutes: 90 }],
  ["H-04", "admin", "Review tools, integrations and subscriptions",
    "Check scheduling, design, AI and analytics tools, app integrations and paid plans. Cancel what isn't used.",
    { proof: "note", leadImpact: "low", minutes: 45 }],
  ["H-05", "content", "Content audit and clean-up",
    "Fix broken links and outdated offers or prices in old posts, pinned content and highlights. Archive what's embarrassing.",
    { proof: "note", performer: "either", minutes: 90 }],
  ["H-06", "reputation", "Collect video testimonials",
    "Record two or more video testimonials with happy clients for use across every platform.",
    { target: 2, unit: "videos", proof: "link", leadImpact: "high", minutes: 120 }],
  ["H-07", "admin", "Back up content and analytics",
    "Download account data, content archives and analytics exports from each platform, and store them with the brand's records.",
    { proof: "note", performer: "either", leadImpact: "low", minutes: 45 }],
  ["H-08", "networking", "Nurture the top 20 relationships",
    "Identify the 20 most valuable relationships (clients, partners, champions) and do something personal for each.",
    { target: 20, unit: "people", proof: "count", leadImpact: "high", minutes: 90 }],
  ["H-09", "profile", "Review legal and policy details",
    "Check privacy links, terms, disclaimers, ad disclosures and regulated wording in bios and on pages.",
    { proof: "note", leadImpact: "low", minutes: 30 }],
]);

/* ================================================================= yearly */

const YEARLY = group("yearly", [
  ["Y-01", "analytics", "Annual social media review",
    "Year-end report: growth, engagement, leads, revenue attributed and cost per platform, best content and key lessons.",
    { proof: "link", performer: "either", leadImpact: "high", minutes: 180 }],
  ["Y-02", "analytics", "Set next year's goals and KPIs",
    "Set follower, engagement, lead and revenue targets per platform, and the activity levels needed to hit them.",
    { proof: "link", leadImpact: "high", minutes: 120 }],
  ["Y-03", "content", "Build the annual content calendar",
    "Map holidays, industry events, launches, awareness days and campaigns for the year into the content plan.",
    { proof: "link", performer: "either", leadImpact: "medium", minutes: 180 }],
  ["Y-04", "profile", "Handles, verification and vanity URLs",
    "Claim the brand handle on new platforms, secure custom URLs, and apply for verification where it's available.",
    { proof: "note", minutes: 60 }],
  ["Y-05", "admin", "Renew paid platform subscriptions",
    "Review and renew or cancel LinkedIn Premium or Sales Navigator, Meta Verified, X Premium and similar plans.",
    { proof: "note", leadImpact: "low", minutes: 30 }],
  ["Y-06", "reputation", "Year-end thank-you and review drive",
    "Thank customers publicly, and ask each active client for a review or testimonial of the year's work.",
    { proof: "count", leadImpact: "high", minutes: 60 }],
  ["Y-07", "content", "Publish a year-in-review post or video",
    "Share the year's highlights, wins, lessons and thank-yous. It's usually one of the best-performing posts of the year.",
    { proof: "link", performer: "either", minutes: 90 }],
  ["Y-08", "admin", "Confirm account ownership and handover",
    "Make sure the company, not an individual, owns every account. Document logins, owners, recovery details and the handover process.",
    { proof: "note", leadImpact: "low", minutes: 60 }],
  ["Y-09", "reputation", "Submit for awards and 'best of' lists",
    "Enter industry awards, directory rankings and 'top company' lists, and promote any wins.",
    { proof: "link", leadImpact: "medium", minutes: 120 }],
  ["Y-10", "profile", "Update company milestones on every profile",
    "Update team size, years in business, awards, certifications, client logos and flagship results across all profiles.",
    { proof: "note", minutes: 45 }],
  ["Y-11", "analytics", "Decide which platforms to join or leave",
    "Evaluate new and declining platforms against where the customers are. Commit to, pause or exit each one.",
    { proof: "note", leadImpact: "medium", minutes: 60 }],
]);

export const ACTIVITY_LIBRARY: LibraryActivity[] = [
  ...DAILY, ...EVERY_2_DAYS, ...WEEKLY, ...MONTHLY, ...QUARTERLY, ...HALF_YEARLY, ...YEARLY,
];
