import { manualPlatform, type ManualSpec } from "./_manual";
import type { Platform } from "../types";

/**
 * Channels worth scheduling into even though they refuse automated posting.
 * Each one still gets composer validation, a calendar slot, and a copy-ready
 * checklist in the publish queue.
 */
const SPECS = [
  // ── Social ──────────────────────────────────────────────────────────────
  { id: "snapchat", name: "Snapchat", color: "#FFFC00", category: "social",
    blurb: "Spotlight clips and Public Profile stories.", why: "organic posting is only exposed to Creative Kit partners.",
    textMax: 250, media: ["image", "video"], requiresMedia: true, mediaMin: 1, hashtags: true },
  { id: "nextdoor", name: "Nextdoor", color: "#8ED500", category: "social",
    blurb: "Neighbourhood posts for local services — high-intent, low reach.", why: "only the Ads API is open to partners.",
    textMax: 3000, media: ["image"] },
  { id: "facebook_group", name: "Facebook Group", color: "#1877F2", category: "social",
    blurb: "Posts inside a Group you own or belong to.", why: "Meta removed Groups publishing from the Graph API.",
    textMax: 5000, media: ["image", "video"] },
  { id: "instagram_broadcast", name: "Instagram Broadcast", color: "#C13584", category: "social",
    blurb: "Broadcast channel blasts to your most engaged followers.", why: "broadcast channels are app-only.",
    textMax: 1000, media: ["image", "video"] },
  { id: "rumble", name: "Rumble", color: "#85C742", category: "video",
    blurb: "Video uploads to an alt-platform audience.", why: "upload access is partner-gated.",
    media: ["video"], requiresMedia: true, mediaMin: 1, mediaMax: 1, needsTitle: true },

  // ── Messaging ───────────────────────────────────────────────────────────
  { id: "whatsapp_channel", name: "WhatsApp Channel", color: "#25D366", category: "messaging",
    blurb: "One-way updates to channel followers.", why: "channels are not part of the Cloud API.",
    textMax: 4096, media: ["image", "video"] },

  // ── Video / audio ───────────────────────────────────────────────────────
  { id: "youtube_community", name: "YouTube Community", color: "#FF0000", category: "video",
    blurb: "Community tab posts, polls and images to your subscribers.", why: "the Community tab has no Data API coverage.",
    textMax: 1500, media: ["image"] },
  { id: "kick", name: "Kick", color: "#53FC18", category: "video",
    blurb: "Stream announcements and clips.", why: "the public API is still unreleased.", textMax: 2000 },
  { id: "soundcloud", name: "SoundCloud", color: "#FF5500", category: "video",
    blurb: "Audio uploads — clips, episodes, tracks.", why: "new upload API keys have been closed for years.",
    media: ["image", "video"], needsTitle: true },
  { id: "spotify_podcast", name: "Spotify for Creators", color: "#1DB954", category: "video",
    blurb: "Podcast episodes distributed through Spotify.", why: "episodes are ingested from your RSS feed, not pushed.",
    needsTitle: true, media: ["video"] },
  { id: "apple_podcast", name: "Apple Podcasts", color: "#9933CC", category: "video",
    blurb: "Podcast episodes on Apple.", why: "Apple pulls from your RSS feed; there is nothing to POST.",
    needsTitle: true },
  { id: "restream", name: "Restream", color: "#1A1A1A", category: "video",
    blurb: "Multistream a live session to every video platform at once.", why: "scheduling a broadcast is a manual studio step.",
    needsTitle: true },

  // ── Publishing ──────────────────────────────────────────────────────────
  { id: "medium", name: "Medium", color: "#000000", category: "blog",
    blurb: "Long-form articles with built-in distribution.", why: "Medium discontinued integration tokens in 2023.",
    textMax: 100000, needsTitle: true, media: ["image"] },
  { id: "substack", name: "Substack", color: "#FF6719", category: "blog",
    blurb: "Newsletter posts that double as public web pages.", why: "there is no public publishing API.",
    textMax: 100000, needsTitle: true, media: ["image"] },
  { id: "slideshare", name: "SlideShare", color: "#0077B5", category: "blog",
    blurb: "Decks and PDFs that rank in search.", why: "the upload API was retired.",
    media: ["document"], requiresMedia: true, mediaMin: 1, needsTitle: true },
  { id: "issuu", name: "Issuu", color: "#F36D5D", category: "blog",
    blurb: "Flipbook publications from PDFs.", why: "publishing needs a paid API plan and manual review.",
    media: ["document"], needsTitle: true },
  { id: "flipboard", name: "Flipboard", color: "#E12828", category: "blog",
    blurb: "Curated magazines that drive referral traffic.", why: "flipping into a magazine is a browser-extension action.",
    textMax: 1000 },

  // ── Communities ─────────────────────────────────────────────────────────
  { id: "quora", name: "Quora", color: "#B92B27", category: "community",
    blurb: "Answers on high-intent questions — evergreen lead source.", why: "Quora has no write API.",
    textMax: 30000, needsTitle: true, steps: ["Find a question with existing traffic before posting a new one"] },
  { id: "hacker_news", name: "Hacker News", color: "#FF6600", category: "community",
    blurb: "Show HN / Launch HN submissions.", why: "submissions are deliberately human-only.",
    textMax: 20000, needsTitle: true, media: [] , mediaMax: 0 },
  { id: "indie_hackers", name: "Indie Hackers", color: "#0E2439", category: "community",
    blurb: "Build-in-public posts to a founder audience.", why: "no public API.", textMax: 20000, needsTitle: true },
  { id: "skool", name: "Skool", color: "#F3AF3D", category: "community",
    blurb: "Community posts and classroom drops.", why: "no public API.", textMax: 20000, needsTitle: true },
  { id: "circle", name: "Circle", color: "#4F46E5", category: "community",
    blurb: "Space posts inside your own community.", why: "the headless API is invite-only.", textMax: 20000, needsTitle: true },
  { id: "mighty_networks", name: "Mighty Networks", color: "#00C2A8", category: "community",
    blurb: "Community and course announcements.", why: "no public write API.", textMax: 20000, needsTitle: true },

  // ── Local, maps & reviews ───────────────────────────────────────────────
  { id: "apple_business", name: "Apple Business Connect", color: "#111111", category: "local",
    blurb: "Showcases on Apple Maps — photos, offers, links.", why: "showcases are managed in Business Connect only.",
    textMax: 200, media: ["image"], requiresMedia: true, mediaMin: 1 },
  { id: "bing_places", name: "Bing Places", color: "#008373", category: "local",
    blurb: "Listing updates and posts on Bing Maps.", why: "no public posting API.", textMax: 1500, media: ["image"] },
  { id: "yelp", name: "Yelp", color: "#D32323", category: "local",
    blurb: "Business updates, offers and Q&A replies.", why: "the Fusion API is read-only.", textMax: 1500, media: ["image"] },
  { id: "tripadvisor", name: "Tripadvisor", color: "#00AA6C", category: "local",
    blurb: "Listing updates and management responses.", why: "content APIs are read-only.", textMax: 2000, media: ["image"] },
  { id: "trustpilot", name: "Trustpilot", color: "#00B67A", category: "local",
    blurb: "Review invitations and public replies.", why: "posting needs a business plan and per-endpoint approval.",
    textMax: 5000 },
  { id: "g2", name: "G2", color: "#FF492C", category: "local",
    blurb: "Profile updates and review campaigns.", why: "only syndication APIs exist.", textMax: 5000 },
  { id: "capterra", name: "Capterra", color: "#FF9D28", category: "local",
    blurb: "Software listing content and review drives.", why: "vendor portal only.", textMax: 5000 },
  { id: "clutch", name: "Clutch", color: "#17313B", category: "local",
    blurb: "Agency profile updates and case studies.", why: "vendor portal only.", textMax: 8000, needsTitle: true },

  // ── Marketplaces & classifieds ──────────────────────────────────────────
  { id: "facebook_marketplace", name: "Facebook Marketplace", color: "#1877F2", category: "commerce",
    blurb: "Listings in front of local buyers.", why: "listings can only be created in the app.",
    textMax: 5000, media: ["image"], requiresMedia: true, mediaMin: 1, needsTitle: true },
  { id: "etsy", name: "Etsy", color: "#F56400", category: "commerce",
    blurb: "Shop updates and listing copy.", why: "listing writes need an approved commercial app.",
    media: ["image"], needsTitle: true },
  { id: "ebay", name: "eBay", color: "#E53238", category: "commerce",
    blurb: "Listings and store announcements.", why: "the Sell API needs a production keyset and review.",
    media: ["image"], needsTitle: true },
  { id: "amazon_posts", name: "Amazon Posts", color: "#FF9900", category: "commerce",
    blurb: "Brand posts shown on product pages.", why: "Posts is brand-registry UI only.",
    media: ["image"], requiresMedia: true, mediaMin: 1, textMax: 2200 },
  { id: "olx", name: "OLX", color: "#002F34", category: "commerce",
    blurb: "Classified listings across emerging markets.", why: "no open listing API.",
    media: ["image"], needsTitle: true },
  { id: "craigslist", name: "Craigslist", color: "#4B0082", category: "commerce",
    blurb: "Local classified ads.", why: "bulk posting is restricted to paid feed partners.",
    media: ["image"], needsTitle: true },
  { id: "gumtree", name: "Gumtree", color: "#72EF36", category: "commerce",
    blurb: "UK/AU classifieds.", why: "no open listing API.", media: ["image"], needsTitle: true },
  { id: "bikroy", name: "Bikroy", color: "#FF7300", category: "commerce",
    blurb: "Bangladesh's largest classifieds marketplace.", why: "no public API.", media: ["image"], needsTitle: true },
  { id: "daraz", name: "Daraz", color: "#F85606", category: "commerce",
    blurb: "South Asian marketplace storefront content.", why: "seller APIs cover catalogue, not marketing posts.",
    media: ["image"], needsTitle: true },
  { id: "gumroad", name: "Gumroad", color: "#FF90E8", category: "commerce",
    blurb: "Product pages and buyer broadcasts.", why: "the API cannot create posts or emails.",
    needsTitle: true },

  // ── Developer, design & directories ─────────────────────────────────────
  { id: "product_hunt", name: "Product Hunt", color: "#DA552F", category: "dev",
    blurb: "Launch day — a concentrated burst of qualified traffic.", why: "launches must be submitted by a human.",
    textMax: 260, needsTitle: true, media: ["image", "video"] },
  { id: "behance", name: "Behance", color: "#1769FF", category: "dev",
    blurb: "Project case studies for design buyers.", why: "project creation is not in the public API.",
    media: ["image", "video"], requiresMedia: true, mediaMin: 1, needsTitle: true },
  { id: "dribbble", name: "Dribbble", color: "#EA4C89", category: "dev",
    blurb: "Shots that feed inbound design enquiries.", why: "shot creation was removed from the API.",
    media: ["image"], requiresMedia: true, mediaMin: 1, needsTitle: true },
  { id: "figma_community", name: "Figma Community", color: "#A259FF", category: "dev",
    blurb: "Free templates as lead magnets.", why: "publishing is a Figma app action.", needsTitle: true },
  { id: "alternativeto", name: "AlternativeTo", color: "#4C5B5C", category: "dev",
    blurb: "Comparison listings that capture switcher intent.", why: "listings are community-submitted.", needsTitle: true },
  { id: "betalist", name: "BetaList", color: "#3369FF", category: "dev",
    blurb: "Early-stage startup exposure.", why: "submissions are a manual form.", needsTitle: true },
  { id: "saashub", name: "SaaSHub", color: "#2D9CDB", category: "dev",
    blurb: "SaaS directory listing and alternatives pages.", why: "submissions are a manual form.", needsTitle: true },
  { id: "crunchbase", name: "Crunchbase", color: "#0288D1", category: "dev",
    blurb: "Company profile updates investors and buyers read.", why: "writes need an enterprise data licence.", needsTitle: true },
  { id: "wellfound", name: "Wellfound", color: "#000000", category: "dev",
    blurb: "Company and job posts to a startup audience.", why: "no public write API.", needsTitle: true },
  { id: "upwork", name: "Upwork", color: "#14A800", category: "dev",
    blurb: "Proposals and profile content for inbound work.", why: "proposal APIs are agency-partner only.", needsTitle: true },
  { id: "fiverr", name: "Fiverr", color: "#1DBF73", category: "dev",
    blurb: "Gig listings and buyer briefs.", why: "no public write API.", needsTitle: true },
  { id: "glassdoor", name: "Glassdoor", color: "#0CAA41", category: "dev",
    blurb: "Employer brand updates — talent and B2B leads.", why: "employer content is portal-only.", needsTitle: true },

  // ── Regional ────────────────────────────────────────────────────────────
  { id: "wechat", name: "WeChat Official Account", color: "#07C160", category: "regional",
    blurb: "Official Account articles — the backbone of China marketing.", why: "publishing requires a mainland business entity and ICP filing.",
    textMax: 20000, needsTitle: true, media: ["image"] },
  { id: "weibo", name: "Weibo", color: "#E6162D", category: "regional",
    blurb: "Microblog posts to a Chinese audience.", why: "API access requires a verified mainland developer account.",
    textMax: 2000, media: ["image", "video"], hashtags: true },
  { id: "douyin", name: "Douyin", color: "#000000", category: "regional",
    blurb: "China's TikTok — short video reach.", why: "open platform access needs a mainland entity.",
    media: ["video"], requiresMedia: true, mediaMin: 1, mediaMax: 1 },
  { id: "xiaohongshu", name: "Xiaohongshu (RED)", color: "#FF2442", category: "regional",
    blurb: "Lifestyle notes with very strong purchase intent.", why: "no API outside the mainland partner programme.",
    textMax: 1000, media: ["image", "video"], requiresMedia: true, mediaMin: 1, hashtags: true },
  { id: "kuaishou", name: "Kuaishou", color: "#FF6600", category: "regional",
    blurb: "Short video for lower-tier Chinese cities.", why: "mainland developer account required.",
    media: ["video"], requiresMedia: true, mediaMin: 1 },
  { id: "bilibili", name: "Bilibili", color: "#00A1D6", category: "regional",
    blurb: "Long-form video for a young Chinese audience.", why: "upload API is partner-gated.",
    media: ["video"], needsTitle: true },
  { id: "zhihu", name: "Zhihu", color: "#0084FF", category: "regional",
    blurb: "China's Quora — expertise-led lead generation.", why: "no public write API.", textMax: 20000, needsTitle: true },
  { id: "naver", name: "Naver Blog / Cafe", color: "#03C75A", category: "regional",
    blurb: "The main search surface in Korea.", why: "blog writes are limited to approved Korean partners.",
    textMax: 20000, needsTitle: true, media: ["image"] },
  { id: "kakao", name: "KakaoTalk Channel", color: "#FEE500", category: "regional",
    blurb: "Direct messages to Korean followers.", why: "message sending needs a Korean business account.",
    textMax: 1000, media: ["image"] },
  { id: "zalo", name: "Zalo Official Account", color: "#0068FF", category: "regional",
    blurb: "Vietnam's dominant messaging channel.", why: "OA messaging requires a Vietnamese business verification.",
    textMax: 2000, media: ["image"] },
  { id: "sharechat", name: "ShareChat / Moj", color: "#E91E63", category: "regional",
    blurb: "Indian-language social and short video.", why: "no public write API.",
    textMax: 1000, media: ["image", "video"], hashtags: true },
] as const satisfies readonly ManualSpec[];

/** Ids covered by the manual catalogue — keeps the platform registry exhaustive at compile time. */
export type ManualPlatformId = (typeof SPECS)[number]["id"];

export const MANUAL_PLATFORMS = Object.fromEntries(
  SPECS.map((spec) => [spec.id, manualPlatform(spec)]),
) as Record<ManualPlatformId, Platform>;
